### ISSUE TITLE
Column moving not displaying properly when inside twitter bootstrap's accordion

### ISSUE THREAD

**Issue by alecogt** [jebaird/dragtable#32]
Hello jebaird. Thanks for your plugin, I've been using it for a while and I really like it.

I noticed that when moving columns inside a twitter bootstrap's accordion component, it leaves a trace of the column you are moving. It moves the column properly, but it doesn't look good. I made a jsfiddle for you to see what I mean: http://jsfiddle.net/g9umse71/3/.

Do you know what's going wrong?
Thank you.

aleco

**Comment by jebaird** [comment]
HI @alecogt , I've never worked with bootstrap accordion widget but it appears that its causing the drag display cleanup to fail.

checkout my working version of your fiddle. http://jsfiddle.net/jebaird/kvv96nxh/

```
$(document).ready(function(){
    $('.table').dragtable({
        stop: function(e, ui){
            $('.dragtable-drag-wrapper').remove();
        }
    });
});
```
On stop I had to force the removal of the drag display. 

Cheers

**Comment by alecogt** [comment]
Excellent, @jebaird, thank you very much.

**Comment by jebaird** [comment]
You're welcome
