### ISSUE TITLE
Not working woth Sorting

### ISSUE THREAD

**Issue by samit2015** [jebaird/dragtable#33]
My Smart table has sorting by-default and if I try to implement swapping of cols with this, my table lost sorting as every action on click on col is being taken as Drag/Drop?

Any suggestions :-)

Thanks
Samit

**Comment by jebaird** [comment]
@samit2015 I've never heard of the plugin "smart table". I you post a jsfiddle I'll be more than happy to take a quick look. 
Cheers

**Comment by samit2015** [comment]
Nvm, I will try  but Smart table is one of the most popular angular based table...which has many functionality by default. Thanks for replying

**Comment by jebaird** [comment]
you're welcome, have a good one
