### ISSUE TITLE
Add textarea to demo page to paste table code

### ISSUE THREAD

**Issue by marcelstoer** [jebaird/dragtable#34]
It'd be nice if I could 
- paste my own table markkup to your demo page
- you'd render it
- I could drag the columns and then
- extract the updated markup

**Comment by jebaird** [comment]
@marcelstoer That's an interesting idea. What problems would it solve?

**Comment by marcelstoer** [comment]
Back when folks were using abhorred editors like Dreamweaver or, for heaven's sake, MS Frontpage it was fairly easy to reorder columns of tables.

The actor for the use case I describe above would be a web developer who uses an editor without WYSIWYG support.

An other case is wiki platforms that use one of hundreds of short-form table syntaxes to render HTML. Many of them give you access to the HTML render but most of them don't support column re-ordering. So, you display the wiki page/component in "source mode", extract the table code mangle it through your demo page feature and paste the result back.

**Comment by jebaird** [comment]
What about a demo in jsfiddle with a button to copy the rendered markup to the clipboard?

**Comment by marcelstoer** [comment]
Hmm, why not, good idea.
