### ISSUE TITLE
Cursor and column move does not match

### ISSUE THREAD

**Issue by sandisahdewo** [jebaird/dragtable#39]
Hi there,
I have a problem with the cursor and the column moving doesn't match when the table is scrolling right
https://drive.google.com/file/d/1aO7ZywDITJTPeFRnJlduYqtJhufFDNFK/view?usp=sharing

As you can see, my cursor has moved to the right (red box), but the moving position of the column (gray box) is still to the left with a distance that is probably the same as the scroll length.

did anyone experience it too?

**Comment by jebaird** [comment]
Hi @sandisahdewo Problems like this are typical related to the markup and or styles of the parent(s) of the table. If you can post an example of your markup jsfiddle or another service I would be happy to take a look

**Comment by sandisahdewo** [comment]
Hi @jebaird  thanks for your feedback.

I found a solution to this problem by adding a few lines of code.

add this line to scroll to the left:
`left += appendTarget.scrollLeft;`
above this code:
```
if( left  < threshold ){
       self._swapCol(self.startIndex-1);
}
```

and also the same thing to scroll to the right.

`left += appendTarget.scrollLeft;`
above this code:
```
if( left  > threshold  && colCount != self.startIndex ){
       self._swapCol( self.startIndex + 1 );
}
```

Thanks for build awesome library :)

**Comment by jebaird** [comment]
you're welcome, glad you were able to figure it out
